tests/mock_*.c: Mark unused function arguments as such.
 This resolves:

 mock_pam.c: In function 'fake_conv':
 mock_pam.c:22:20: error: unused parameter 'num_msg' [-Werror=unused-parameter]
    22 | int fake_conv (int num_msg, const struct pam_message **msg,
       |                ~~~~^~~~~~~
 mock_pam.c:23:39: error: unused parameter 'appdata_ptr' [-Werror=unused-parameter]
    23 |     struct pam_response **resp, void *appdata_ptr)
       |                                 ~~~~~~^~~~~~~~~~~
 mock_pam.c: In function 'fake_conv_empty_password':
 mock_pam.c:51:35: error: unused parameter 'num_msg' [-Werror=unused-parameter]
    51 | int fake_conv_empty_password (int num_msg, const struct pam_message **msg,
       |                               ~~~~^~~~~~~
 mock_pam.c:52:39: error: unused parameter 'appdata_ptr' [-Werror=unused-parameter]
    52 |     struct pam_response **resp, void *appdata_ptr)
       |                                 ~~~~~~^~~~~~~~~~~
 cc1: all warnings being treated as errors